### ISSUE TITLE
paraview 5.9.1 crash when vtk to vdb exporting 

### ISSUE THREAD

**Issue by brioglade** [acbauer/ParaViewVDBWriterPlugin#1]
So what's the problem.It will be interrupted and shut-off when using the ParaViewVDBWriterPlugin.
Please help me.I really need this greatly exporter to transform my data.
https://drive.google.com/file/d/1YIGLg-jnO33rvjuhsO7IwwPqjEfHLIY5/view?usp=sharing
Thank you very much.

**Comment by acbauer** [comment]
This project is not in development. Please use ParaView master instead -- https://gitlab.kitware.com/paraview/paraview. The goal is to have this writer in ParaView 5.10, which should be release in the fall of 2021.
